### PR TITLE
Continue #27: Support multi-threaded compression

### PR DESCRIPTION
**Pull request by kokobd**
This is based on #27 with a minor version bump and some new tests. Closes #27.

### CODE REVIEW

**Comment by phadej** [comment]
Interesting, that mac failure.

Which liblzma version the multithreading was introduced. Maybe it's time to use `pkgconfig` by default.

**Comment by phadej** [comment]
So the minimum version is 5.2.0: https://github.com/xz-mirror/xz/blob/master/NEWS#L1085-L1110

In #34 I added a pkgconfig-depends asking for 5.2.2 (the version on ubuntu 18.04 used for CI atm).

Could you rebase on top of current `master`.

**Comment by kokobd** [comment]
And, strangely, it works with ghc-9.2 on macOS. It might be related to ghc-9.4.1. Let's rerun the CI and see.

**Comment by kokobd** [comment]
@phadej can we merge this?

**Comment by phadej** [comment]
https://hackage.haskell.org/package/lzma-0.0.1.0 with this patch is on Hackage

**Pull request closed without merging**
